### ISSUE TITLE
国家選択GUIの戻るボタン

### ISSUE THREAD

**Issue by RinMC6226** [Min4r/Tsareich#2]
戻るボタンが反応しない。
地図の画面まで出してから戻ることで最初のメニューに戻れる

**Comment by Nyuhei** [comment]
おそらくシナリオが一つしかないとスキップされる仕組みになっていて、国家選択画面の戻るはシナリオ選択画面に繋がっているので
メイン→シナリオ（一つしかないのでスキップ）→国家→シナリオ（一つしかないのでスキップ）→国家→…というような状況になっていると推測

**Comment by Nyuhei** [comment]
１９３６を２つにすることで解決しました

**Comment by RinMC6226** [comment]
えぐ
